search_space:
  activation:
    _type: choice
    _value: [['dice', 'dice'], ['relu', 'relu']]
  dice_momentum:
    _type: choice
    _value: [0.8]
  seed:
    _type: choice
    _value: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

trial_command: python din_training.py
trial_code_directory: ..

trial_concurrency: 6
max_trial_number: 100

tuner:
  name: GridSearch

training_service:
  platform: local